name: linux-q5go # you probably want to 'snapcraft register <name>'
base: core18 # the base snap is the execution environment for this snap
version: '1.0.0' # just for humans, typically '1.2+git' or '1.3.2'
summary: SGF Editor and online Go playing client
description: |
  SGF Editor and online Go playing client

grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots
icon: GoBoard.png
title: q5go

apps:
  q5go:
    command: build/q5go
parts:
  q5go:
    # See 'snapcraft plugins'
    plugin: dump
    source: .
    build-packages: [qtcreator, qtbase5-dev, qt5-qmake, cmake, libqt5svg5-dev, qtmultimedia5-dev]
    stage-packages: [qtcreator, qtbase5-dev, qt5-qmake, cmake, libqt5svg5-dev, qtmultimedia5-dev]
    organize:
      q5go: build/
      q5go.1: man/man1/

architectures:
  - build-on: amd64

